### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by eventualbuddha**

### CODE REVIEW

**Comment by vslinko** [comment]
@eventualbuddha I want to transfer this repo into your account because I don't use ES6 right now. What are you think?

**Comment by eventualbuddha** [comment]
Sounds good. If you want to make me an admin of this repo I can move it to esnext and keep you as a collaborator.

**Comment by vslinko** [comment]
@eventualbuddha done

**Comment by eventualbuddha** [comment]
I don't seem to be able to do anything with the repo (except push to it). The official way to do this, I think, is to make you an admin over no repos in the esnext repo (which I just did) and let you transfer the repos there yourself. Mind doing that? Thanks!

**Comment by vslinko** [comment]
@eventualbuddha done

**Comment by vslinko** [comment]
I suggest that I should share npm access to these modules. What is you npm account?

**Comment by eventualbuddha** [comment]
@vslinko eventualbuddha, same as GitHub.

**Comment by vslinko** [comment]
@eventualbuddha done

**Pull request merged**
